# -*- coding: utf-8 -*-
"""
flatfield.py

This script updates the dotcorrect coefficients for the display panel
based on panel_config.npz as generated by test_panel.py
and on pixel_stats.npz as generated by pixel_stats.py

To save the updated dotcorrect coefficients to the display panel you
need to re-run test_panel.py with "reset_config = False" and "save_config = True"

"""
import numpy as np
import os

config_path = 'board 2'
config_file = os.path.join(config_path,'panel_config.npz')
stats_file = os.path.join(config_path, 'pixel_stats.npz')

print(f'Loading "{config_file}"')
with np.load(config_file,allow_pickle=True) as cfg:
    serial = cfg['serial']
    mode = cfg['mode']
    maxcurrent = cfg['maxcurrent']
    brightness = cfg['brightness']
    dotcorrect = cfg['dotcorrect']
    spif = cfg['spif']

print(f'Loading "{stats_file}"')
with np.load(stats_file) as stats:
    means = stats['means']

print('Adjusting dotcorrect coefficients')
#adjust dotcorrect values by the pixel stats, then renormalize them
dotcorrect *= np.nanmin(means, (0,1))/means
dotcorrect /= np.max(dotcorrect,(0,1))

print(f'Rename "{config_file}" -> "{config_file}.old"')
os.rename(config_file, config_file+'.old')
print(f'Saving "{config_file}"')
np.savez(config_file,serial=serial,mode=mode,maxcurrent=maxcurrent,brightness=brightness,dotcorrect=dotcorrect,spif=spif)
